export type Language = 'nl' | 'en';

const corpora: Record<Language, string[]> = {
  nl: [
    'Op een vroege zaterdagochtend hing er nog nevel boven het water. Langs het pad reed een fietser rustig richting de oude brug, terwijl in de verte de eerste winkels hun deuren openden. De bakker zette een houten bord buiten en veegde het laatste meel van zijn schort. Bij het plein wachtte een hond geduldig naast een bankje. Niemand leek haast te hebben.',
    'In de bibliotheek viel het zonlicht in lange banen over de vloer. Mara zocht een boek over oude kaarten, maar bleef hangen bij een kast vol reisverhalen. Ze bladerde door een verslag van een tocht langs kleine eilanden en vergat even waarom ze gekomen was. Buiten reden bussen af en aan. Binnen hoorde je alleen papier, zachte stappen en af en toe een stoel.',
    'Na de lunch trok het team de wandelschoenen aan. Het pad begon breed tussen de velden, maar werd smaller zodra het bos dichter werd. Regen van de vorige nacht glansde nog op de bladeren. Bij iedere bocht veranderde het uitzicht. Na een uur bereikten ze een open plek waar een eenvoudige tafel stond. Daar deelden ze koffie en brood.',
    'De trein vertrok precies op tijd en liet de drukte van het station snel achter zich. Huizen maakten plaats voor weilanden, sloten en rijen populieren. Een reiziger werkte op zijn laptop, twee kinderen telden windmolens en iemand schonk thee uit een kleine thermoskan. Toen de conducteur langskwam, was de stad al niet meer aan de horizon te zien.',
    'Elke woensdag kookten de buren samen in de grote keuken beneden. De ene week stond er soep op tafel, de volgende week maakte iemand een gerecht uit een familieboek. Er werd geproefd, bijgestuurd en veel gepraat. Nieuwe bewoners hoefden niets mee te brengen. Aan het einde verdeelden ze wat over was in bakjes voor de volgende dag.',
    'Aan het einde van de middag werd de werkplaats stiller. Gereedschap ging terug aan de muur en het zaagsel werd bij elkaar geveegd. Op de middelste tafel stond een bijna voltooide stoel. De verbindingen sloten precies en het hout voelde glad aan. Alleen de zitting moest nog worden afgewerkt. Dat werk kon beter wachten tot het ochtendlicht.',
    'Het kleine cafe aan de haven had maar zes tafels. Vanaf het raam kon je zien hoe boten langzaam draaiden met het tij. Een vrouw schreef in een schrift, onderbrak zichzelf voor een slok koffie en keek daarna weer naar buiten. De eigenaar kende bijna iedereen bij naam. Voor bezoekers had hij altijd een goed verhaal over het weer.',
    'In september begon de tuin opnieuw te veranderen. De felle kleuren van de zomer werden zachter en spinnenwebben verschenen tussen de struiken. Tom verzamelde zaden in papieren zakjes en schreef zorgvuldig de namen erop. Wat nu klein en droog leek, zou in het voorjaar weer uitgroeien tot hoge bloemen waar bijen op afkwamen.',
    'Voor de vergadering legde Noor haar telefoon in een lade en schreef drie vragen op papier. Dat eenvoudige ritueel hielp haar om beter te luisteren. Het gesprek duurde korter dan gepland, omdat iedereen wist welk besluit nodig was. Na afloop bleef er tijd over om de eerste taak meteen samen uit te voeren.',
    'De markt liep langzaam leeg toen donkere wolken boven de daken verschenen. Handelaren vouwden hun kramen in en stapelden lege kisten op elkaar. Een laatste klant koos appels voor een taart. Nog voor de regen begon, reed de groentewagen de straat uit en rook het plein naar natte stenen en verse kruiden.',
    'Op kantoor begon de dag met een kort overzicht van het werk. Iedereen noemde een taak die af moest en een vraag waarbij hulp welkom was. Daarna verdwenen de meeste mensen achter hun scherm. Tegen de middag was een lastig probleem opgelost, niet door een lange vergadering maar door vijf minuten samen naar dezelfde code te kijken.',
    'De veerboot voer langzaam weg van de kade. Meeuwen bleven nog even naast het dek hangen en keerden toen terug naar de haven. Aan boord zochten reizigers een plek uit de wind. Een jongen wees naar een vuurtoren die steeds kleiner werd. Voor hem was de overtocht al een avontuur voordat het eiland in zicht kwam.',
    'Tijdens de training lag de nadruk niet op snelheid maar op een gelijkmatig tempo. De lopers begonnen rustig en hielden genoeg energie over voor de laatste ronde. Langs het veld noteerde de trainer de tijden in een klein boekje. Na afloop bleek bijna iedereen sneller te zijn dan vorige week, zonder dat het zwaar had gevoeld.',
    'Sara repareerde oude radio toestellen aan een tafel bij het raam. Ze begon altijd met schoonmaken en keek daarna welke onderdelen nog goed waren. Soms was een losse draad het hele probleem. Op andere dagen kostte het uren om een storing te vinden. Het mooiste moment bleef hetzelfde: de eerste heldere stem uit een toestel dat lang stil was geweest.',
    'In de keuken stond een pan saus zacht te koken. Amir proefde, voegde wat peper toe en draaide het vuur lager. Het recept gaf exacte hoeveelheden, maar hij vertrouwde ook op geur en kleur. Terwijl het brood in de oven bruin werd, dekte hij de tafel. Er was niets ingewikkelds aan het eten, maar iedereen bleef lang zitten.',
    'De ochtend na de storm lag het strand vol aangespoeld hout. Vrijwilligers liepen met grote zakken langs de vloedlijn en sorteerden afval van natuurlijke resten. Tussen het wier vonden ze een blauwe emmer, een kapotte boei en tientallen doppen. Na twee uur was het verschil duidelijk zichtbaar en dronken ze warme thee achter de duinen.',
    'Een nieuwe fietsroute verbond het dorp met het station. Eerst waren er vooral vragen over kosten en ruimte, maar na een paar maanden gebruikten scholieren en reizigers het pad iedere dag. De oude weg voelde rustiger en de fietsenstalling stond vaak vol. Wat op papier een kleine verandering leek, veranderde voor veel mensen hun dagelijkse reis.',
    'In het museum werkte een restaurator aan een groot landschap. Onder een vergeelde laag kwam langzaam een heldere lucht tevoorschijn. Iedere beweging gebeurde met een klein penseel en veel geduld. Bezoekers zagen meestal alleen het eindresultaat, maar op deze middag konden ze door een glazen wand volgen hoeveel aandacht een paar centimeter verf nodig had.',
    'Rond zonsondergang zette de sterrenwacht de koepel open. De lucht was helder genoeg om een verre planeet te zien, al leek die door het blote oog niet meer dan een heldere stip. Een vrijwilliger stelde de telescoop scherp en legde uit waarom het beeld soms trilde. Iedere bezoeker mocht even kijken en kwam stil van het trapje terug.',
    'De klas kreeg de opdracht om een brug van papier te bouwen. Eerst ontstonden wilde plannen met torens en kabels, maar bij de eerste test zakten veel ontwerpen direct in. Daarna werd er gevouwen, gemeten en opnieuw geprobeerd. De sterkste brug zag er uiteindelijk eenvoudig uit en droeg meer boeken dan iemand vooraf had verwacht.',
    'Op de camping werd het langzaam donker. Iemand stak een lamp aan en legde een kaart op tafel voor de route van morgen. Vanuit het bos klonk af en toe een vogel, verder was het stil. De dag had meer kilometers gebracht dan gepland. Toch besloot de groep vroeg te vertrekken, omdat het uitzicht vanaf de heuvel de klim waard zou zijn.',
    'De fotograaf kwam vaak terug naar dezelfde straathoek. Niet omdat het gebouw bijzonder was, maar omdat het licht ieder uur iets anders deed. In de ochtend lagen lange schaduwen over de stoep. Rond de middag glansden de ramen en tegen de avond kleurde de gevel warm. De plek bleef gelijk, terwijl elke foto een ander verhaal vertelde.'
  ],
  en: [
    'Early on Saturday morning, a thin mist still floated above the water. A cyclist followed the path toward the old bridge while the first shops opened in the distance. The baker placed a wooden sign outside and brushed flour from his apron. Near the square, a dog waited patiently beside a bench. Nobody seemed to be in a hurry.',
    'Sunlight fell in long stripes across the library floor. Maya was looking for a book about old maps, but stopped at a shelf filled with travel stories. She opened an account of a journey between small islands and briefly forgot why she had come. Buses moved outside. Inside, there was only paper, quiet footsteps, and an occasional chair.',
    'After lunch, the group put on their walking shoes. The path began wide between the fields, then narrowed as the forest grew thicker. Rain from the previous night still shone on the leaves. The view changed at every turn. After an hour they reached a clearing with a simple table, where they shared coffee and bread.',
    'The train left exactly on time and quickly moved beyond the busy station. Houses gave way to fields, narrow canals, and rows of tall trees. One traveler worked on a laptop, two children counted windmills, and someone poured tea from a small flask. By the time the conductor arrived, the city had disappeared from the horizon.',
    'Every Wednesday, the neighbors cooked together in the large kitchen downstairs. One week there was soup, and the next someone prepared a dish from an old family notebook. They tasted, adjusted, and talked. New residents did not need to bring anything. At the end, they divided the leftovers into containers for the following day.',
    'The workshop became quieter late in the afternoon. Tools returned to the wall and sawdust was swept into a neat pile. An almost finished chair stood on the center table. Its joints met precisely and the wood felt smooth. Only the seat still needed attention. That work could wait for the clear light of morning.',
    'The small cafe by the harbor had only six tables. Through the window, visitors could watch boats turn slowly with the tide. A woman wrote in a notebook, paused for a sip of coffee, and looked outside again. The owner knew nearly everyone by name. For visitors, he always had a good story about the weather.',
    'In September, the garden began to change again. The bright colors of summer became softer and spider webs appeared between the shrubs. Tom collected seeds in paper bags and carefully wrote a name on each one. What seemed small and dry now would grow into tall spring flowers that attracted bees from across the neighborhood.',
    'Before the meeting, Nora put her phone in a drawer and wrote three questions on paper. That simple ritual helped her listen more carefully. The conversation ended early because everyone understood which decision was needed. Afterwards, there was enough time to begin the first task together instead of scheduling another meeting.',
    'The market slowly emptied when dark clouds appeared above the roofs. Traders folded their stalls and stacked empty crates. One final customer chose apples for a pie. Before the rain began, the vegetable truck turned out of the street and the square smelled of wet stone and fresh herbs.',
    'At the office, the day began with a short review of the work ahead. Everyone named one task to finish and one question where help might be useful. Most people then returned to their screens. Before lunch, a difficult problem was solved through five minutes of looking at the same code together instead of another long meeting.',
    'The ferry moved slowly away from the quay. Seagulls followed beside the deck for a while before turning back toward the harbor. Passengers found places out of the wind. A young boy pointed at a lighthouse that grew smaller behind them. For him, the crossing was already an adventure before the island came into view.',
    'The training session focused on a steady pace rather than pure speed. The runners started gently and saved enough energy for the final lap. Beside the field, the coach wrote their times in a small notebook. Afterwards, nearly everyone had improved since the previous week, even though the session had never felt unusually hard.',
    'Sarah repaired old radios at a table beside the window. She always began by cleaning them and checking which parts still worked. Sometimes a loose wire was the entire problem. On other days, finding a fault took hours. The best moment was always the same: hearing the first clear voice from a radio that had been silent for years.',
    'A pan of sauce simmered quietly in the kitchen. Amir tasted it, added a little pepper, and lowered the heat. The recipe offered exact amounts, but he also trusted color and smell. While bread turned brown in the oven, he set the table. The meal was simple, yet everyone stayed in their seat long after finishing it.',
    'The morning after the storm, the beach was covered with driftwood. Volunteers walked along the tide line with large bags and separated rubbish from natural debris. Among the seaweed they found a blue bucket, a broken buoy, and dozens of plastic caps. After two hours, the improvement was clear, and they shared hot tea behind the dunes.',
    'A new cycle route connected the village to the railway station. At first, people mainly asked about cost and space, but within months students and commuters used the path every day. The old road became quieter and the bicycle racks were often full. What looked like a small change on paper transformed many daily journeys.',
    'At the museum, a restorer worked on a large landscape painting. Beneath a yellowed layer, a bright sky slowly appeared. Every movement required a small brush and great patience. Visitors usually saw only the finished result, but that afternoon they could watch through a glass wall and discover how much care a few inches of paint required.',
    'Around sunset, the observatory opened its dome. The sky was clear enough to reveal a distant planet, although it looked like little more than a bright point to the naked eye. A volunteer focused the telescope and explained why the image sometimes trembled. Each visitor took a turn and returned from the steps in thoughtful silence.',
    'The class was asked to build a bridge from paper. Their first designs included ambitious towers and cables, but many collapsed during the opening test. The students folded, measured, and tried again. The strongest bridge eventually looked surprisingly simple and supported more books than anyone had expected before the lesson began.',
    'Night settled slowly over the campsite. Someone switched on a lantern and spread a map across the table to plan the next route. A bird called from the forest, but otherwise the area was quiet. The day had been longer than expected. Even so, the group chose an early start because the view from the hill promised to be worth the climb.',
    'The photographer often returned to the same street corner. The building itself was ordinary, but the light changed its character every hour. Long shadows crossed the pavement in the morning. At noon, the windows shone, and by evening the front wall glowed warmly. The place remained still while each photograph told a different story.'
  ]
};

export function makeWords(language: Language, amount: number, random = Math.random): string[] {
  const paragraphs = [...corpora[language]];
  for (let i = paragraphs.length - 1; i > 0; i--) {
    const swapWith = Math.floor(random() * (i + 1));
    [paragraphs[i], paragraphs[swapWith]] = [paragraphs[swapWith], paragraphs[i]];
  }
  const pool = paragraphs.flatMap(p => p.split(/\s+/));
  const result: string[] = [];
  while (result.length < amount) {
    result.push(...pool);
  }
  return result.slice(0, amount);
}
